---
title: "Enrichment"
author: "almut"
date: "30 Mai 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Enrichment tests on different gene sets and different methods
### Functions to run enrichment tests and plot results using variable gene sets and methods

```{r library}
library(topGO)
library(org.Hs.eg.db)
library(circlize)
library(piano)
library(tidyverse)
library(ggpubr)
```

```{r gene sets}
#load gene set collection
#Hallmark
gsc <- loadGSC("/home/almut/Dokumente/masterarbeit/data/h.all.v6.0.symbols.gmt", type="gmt")
#Kegg
gsc_Kegg <- loadGSC("/home/almut/Dokumente/masterarbeit/data/c2.cp.kegg.v6.0.symbols.gmt", type="gmt")
tft <- loadGSC("/home/almut/Dokumente/masterarbeit/data/c3.tft.v6.0.symbols.gmt", type="gmt")
c5 <- loadGSC("/home/almut/Dokumente/masterarbeit/data/c5.all.v6.0.symbols.gmt", type="gmt")
c6 <- loadGSC("/home/almut/Dokumente/masterarbeit/data/c6.all.v6.0.symbols.gmt", type="gmt")
c7 <- loadGSC("/home/almut/Dokumente/masterarbeit/data/c7.all.v6.0.symbols.gmt", type="gmt")
cgp <- loadGSC("/home/almut/Dokumente/masterarbeit/data/c2.cgp.v6.0.symbols.gmt", type="gmt")
```

## Piano
```{r piano, fig.width=16, fig.height=7}
piano <- function(variant, gmtFile){
  diff_res <- read.csv(file=paste0("/home/almut/Dokumente/masterarbeit/results/noTsig/", variant ,"_diffGenes.csv"))
  #needs to be symbol/remove those without symbol, but ENSID only
  diff_res <- diff_res[-which(diff_res$Symbol %in% c("", NA)),]
  #get genes and pvalues 
  geneNam <- diff_res$Symbol 
  pVal <- diff_res$padj
  gsTab <- data.frame(gene = geneNam, stat = pVal)
  gsaTab <- data.frame(row.names = gsTab$gene, stat = gsTab$stat)
  res <- runGSA(geneLevelStats = gsaTab,
                      geneSetStat = "fisher",
                     adjMethod = "fdr", gsc=gmtFile,
                     signifMethod = "geneSampling",
                      nPerm = 50000,
                      gsSizeLim=c(1, Inf))
  Res <- arrange(GSAsummaryTable(res),desc(`Stat (non-dir.)`))
  #rename results to plot
  resPlot <- Res[, c(1:5)]
  colnames(resPlot) <- c("pathway", "gene_number", "stat", "p", "p.adj")
  #Prepare for plotting
  enrichPlot <- resPlot[c(1:10),] %>% mutate(log10Padj = -log10(p.adj)) %>% mutate(genes = ifelse(gene_number > 5, ">5", "<=5"))
  #plot
  p <- ggbarplot(enrichPlot, x = "pathway", y = "log10Padj",
          fill = "genes",           # change fill color by mpg_level
          color = "white",            # Set bar border colors to white
          palette = "jco",            # jco journal color palett. see ?ggpar
          sort.val = "asc",          # Sort the value in ascending order
          sort.by.groups = FALSE,     # Don't sort inside each group
          x.text.angle = 90,          # Rotate vertically x axis texts
          ylab = "-log10(padj)",
          legend.title = "Pathway",
          rotate = TRUE,
          font.x = 20, font.y = 20, font.legend = 20, legend = "right", 
          title = paste(variant),
          ggtheme = theme_pubr()
          ) + font("xy.text", size = 22) + font("title", size = 20, face = "bold")
  
  #ggsave(file=paste0("/home/almut/Dokumente/masterarbeit/results/noTsig/enrichment/kegg/GSEA_in_", variant, ".pdf"), plot=p, width=16, height=7)
  p
}

vars <- c("IGHV", "trisomy12", "del13q14", "del8p12", "gain8q24", "del11q22.3", "del17p13", "BRAF", "NOTCH1", "SF3B1", "TP53", "ATM", "MED12")

#resListGSA <- 
lapply(vars, FUN = "piano", gmtFile = gsc_Kegg)


```


