---
title: "abruzzo_epistasis"
author: "almut"
date: "25 March 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Epistasis in Abruzzo et al., 2017 trisomy12 data

libraries
```{r libs}
suppressPackageStartupMessages({
  library(limma)
  library(here)
  library(DESeq2)
  library(magrittr)
  library(dplyr)
  library(ggplot2)
  library(ggpubr)
  library(RColorBrewer)
  library(ComplexHeatmap)
  library(purrr)
  library(circlize)
})
```

Data
```{r data}
data_dir = here("data")
express <- read.csv(paste0(data_dir, "/abruzzo/expressionData.csv"))
features <- read.csv(paste0(data_dir, "/abruzzo/probeFeatures.csv"))
clinical <- read.csv(paste0(data_dir, "/abruzzo/safeClinical.csv"))


```

Filter patients
```{r filter pat}
filtered_id <- clinical %>% filter(Purity %in% c("Tri12", "Diploid")) %>% select(X)
rownames(express) <- express$X
express <- express[, colnames(express) %in% filtered_id$X]
filtered_clin <- clinical %>% filter(Purity %in% c("Tri12", "Diploid"))
```

### Preprocess probes
```{r}
sds <- rowSds(as.matrix(express))
exprMat <- as.matrix(express)[order(sds, decreasing = T)[1:10000],]
```



### Limma
```{r design}
ighv <- factor(filtered_clin$mutation.status, levels=c("U","M"))
tri12 <- factor(filtered_clin$Purity, levels=c("Tri12","Diploid"))

design <- model.matrix(~ ighv + tri12 + ighv:tri12)
fit <- lmFit(exprMat, design)
fit <- eBayes(fit)

fit3 <- contrasts.fit(fit, c(0,-1, -1, 1))
fit3 <- eBayes(fit3)
top3 <- topTable(fit3, adjust="BH")
```

### results
```{r res plot}
plotMDS(exprMat,labels=filtered_clin$Purity)
pcaRes <- prcomp(t(exprMat), scale =T)
varExp <- (pcaRes$sdev^2 / sum(pcaRes$sdev^2)) * 100
pcaTab <- data.frame(pcaRes$x[,c(1:10)])
names(varExp) <- colnames(pcaRes$x)

pcaTab <- cbind(pcaTab, filtered_clin[, c("Purity", "mutation.status")])


```

pca
```{r pca ighv}
p <- ggscatter(pcaTab, x = "PC1", y = "PC2", color = "mutation.status", palette = "jco", size = 3,
  ylab = sprintf("PC2 (%2.1f%%)",varExp[2]), xlab = sprintf("PC1 (%2.1f%%)",varExp[1]), 
  legend = "right", main = "PCA coloured by IGHV status", 
  font.legend = c(23, "plain", "black"), 
  font.tickslab = c(23, "plain", "black"), 
  font.main = 25, font.submain = 28, font.caption = 28, font.x = 28, font.y= 28) + 
  coord_fixed()

p
```

trisomy12
```{r pca tri12}

p <- ggscatter(pcaTab, x = "PC1", y = "PC2", color = "Purity", palette = "jco", size = 3, shape = "mutation.status",
  ylab = sprintf("PC2 (%2.1f%%)",varExp[2]), xlab = sprintf("PC1 (%2.1f%%)",varExp[1]), 
  legend = "right", main = "PCA coloured by Trisomy12 status") + 
  coord_fixed()

p
```

Top DE genes related to the interaction
```{r top expr mat}
diff <- fit3$p.value %>% as.vector() %>% set_names(rownames(fit3$p.value))
exprVariant <- exprMat[order(diff, decreasing = F)[1:100],]
exprVariant.new <- t(scale(t(exprVariant)))
exprVariant.new[exprVariant.new > 4] <- 4
exprVariant.new[exprVariant.new < -4] <- -4

rownames(features) <- features$X
gene_names <- data.frame("probes" = rownames(exprVariant), 
                         "gene" = features[rownames(exprVariant), "SYMBOL"])
gene_names$gene <- ave(gene_names$gene, gene_names$gene, FUN = function(i) paste0(i, '_', seq_along(i)))
rownames(exprVariant.new) <- gene_names$gene
```


Heatmap
```{r heatmap, fig.width=8, fig.height=14}
mutnames <- c("IGHV-UM", "IGHV-M", "tri12_IGHV-UM", "tri12_IGHV-M")
  
  mutStatus <- data.frame(filtered_clin) %>% mutate(IGHV = ifelse(mutation.status %in% "M", 1, 0)) %>% 
    mutate(tri12 = ifelse(Purity %in% "Tri12", 1, 0)) %>% 
    dplyr::select_("X", "IGHV", "tri12") %>% 
    mutate_("namA" = "IGHV", "namB" = "tri12") %>% 
    mutate(naA = as.numeric(as.character(namA))) %>% 
    mutate(naB = as.numeric(as.character(namB))) %>% 
    mutate(mut = factor(mutnames[1 + naA + 2 * naB], levels = mutnames)) %>% arrange(mut)
  
  exprVariant.new <- exprVariant.new[,mutStatus$X]
  
  #colors
  #colors <- colorRampPalette( rev(brewer.pal(11,"RdBu")) )(255)
  colors = colorRamp2(c(-4, -1, 0, 1, 4), c("#2166ac", "#4393c3", "#f7f7f7", "#d6604d", "#b2182b"))
  annocol <- get_palette("uchicago", 9)
  
  annocolor <- list(Variant = c("IGHV-UM" = annocol[3], "IGHV-M" = annocol[5], "tri12_IGHV-UM" = annocol[7], "tri12_IGHV-M" = annocol[9]))
  names(annocolor$Variant) <- c("IGHV-UM", "IGHV-M", "tri12_IGHV-UM", "tri12_IGHV-M")
  mutationStatus <- data.frame(mutStatus$mut)
  rownames(mutationStatus) <- mutStatus$X
  colnames(mutationStatus) <- "Variant"
  #Column annotation
  ha_col = HeatmapAnnotation(df = mutationStatus, col = annocolor, annotation_height = unit(1.8, "cm"),
                             annotation_legend_param = list(title_gp = gpar(fontsize = 23), 
                                                            labels_gp = gpar(fontsize = 18),  
                                                            grid_height = unit(0.7, "cm"), 
                                                            grid_width = unit(0.3, "cm"), 
                                                            gap = unit(15, "mm")))
  #rowcluster
  geneExpression_dist <- dist(exprVariant.new)
  rowcluster = hclust(geneExpression_dist, method = "ward.D2")
  #heatmap
  h1 <- Heatmap(exprVariant.new, 
                col = colors,
                column_title = paste0("Gene interactions:", "IGHV", "-", "trisomy12"), 
                column_title_gp = gpar(fontsize = 23, fontface = "bold"), 
                heatmap_legend_param = list(title = "Expr", 
                                            title_gp = gpar(fontsize = 23), 
                                            grid_height = unit(0.7, "cm"), 
                                            grid_width = unit(0.3, "cm"), 
                                            gap = unit(15, "mm"), 
                                            labels_gp = gpar(fontsize = 18), 
                                            labels = c(-4, -1, 0, 1, 4)), 
                row_dend_width = unit(0.7, "cm"), 
                show_row_dend = T, 
                show_column_names =FALSE ,
                top_annotation = ha_col,
                show_row_names = TRUE, 
                show_column_dend = FALSE, 
                row_title_gp = gpar(fontsize = 0),
                cluster_columns = FALSE, 
                cluster_rows = rowcluster, 
                split = 4, gap = unit(0.2,"cm"), 
                column_order = mutStatus$X)


IGHVTri12 <- list("sig_Genes" = gene_names$gene, "geneExp" = exprVariant.new, "h1"= h1)
p1 <- draw(h1) 
saveRDS(p1, file = paste0(output_dir, "/figures/r_objects/epistasis/epistasis_heatmap_abruzzo.rds"))
```

Genewise expression
```{r genewise, fig.width=10, fig.height=6}
cluster <- c("synergy", "buffering", "supression", "inversion")
gene_by_cat <- lapply(1:4, function(clusternr){
  genes <- IGHVTri12$sig_Genes[row_order(IGHVTri12$h1)[[clusternr]]]
}) %>% set_names(cluster)

#Add int probes to gene_names and expr
int_probes <- features[features$SYMBOL %in% c("EBF1", "FGF2","LEF1"), c("X", "SYMBOL")]
colnames(int_probes) <- c("probes", "gene")
gene_names <- rbind(gene_names, int_probes)
exprVariant <- rbind(exprVariant, as.matrix(express[int_probes$probes,]))

#function to create stripchart plots for specific genes
gene_count <- function(probe){
  gene_nam <- gene_names$gene[which(gene_names$probe %in% probe)]
  gene_cat <- names(gene_by_cat) %>% map(function(cat){
    cat_gene <- "none"
    cat_gene <- ifelse(any(gene_nam %in% gene_by_cat[[cat]]), cat, cat_gene) 
    }) %>% unlist()
  #gene_cat <- gene_cat[!gene_cat %in% "none"]
  gene_cat <- ifelse(gene_nam %in% "EBF1", "synergy", gene_cat)
  gene_cat <- ifelse(gene_nam %in% "FGF2", "suppression", gene_cat)
  gene_count = data.frame("counts" = exprVariant[probe,], mut_status = mutationStatus[colnames(exprVariant), "Variant"])
  p <- ggboxplot(gene_count, x = "mut_status", y = "counts",
          color = "mut_status",
          size = 1.2,
          palette = c(annocol[3], annocol[5], annocol[7], annocol[9]),
          add = "jitter",
          outlier.shape = NA,
          add.params = list(size = 2.5),
          #yscale = "log10",
          title = paste0(gene_nam, ": ", gene_cat),
          font.x = 20, font.y = 20, font.legend = 20, 
          ylab = "normalised intensities") + font("xy.text", size = 20) + font("title", size = 20, face = "bold")
  saveRDS(p, file = paste0(output_dir, "/figures/r_objects/epistasis/abruzzo/de_genes/", gene_nam, ".rds"))
  p
}
#interesting genes
geneList <- gene_names$probes[1:30]
geneList <- c(geneList, int_probes$probes)
lapply(geneList, gene_count)


```

